name: Update Trophy
on:
  schedule:
    - cron: "0 0 * * *" # Daily midnight update
  workflow_dispatch: # Manual trigger button

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Permission to write to repo
    permissions:
      contents: write

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        # Force install taaki version conflict na ho
        run: npm install node-fetch@2 --force

      - name: Fetch GitHub data and update SVG
        run: |
          node src/fetchData.js
          node src/generateTrophy.js 

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          
          # ðŸ”¥ Yahan change hai: trophy_*.svg saari themes ko add kar lega
          git add trophy_*.svg data.json 
          
          git commit -m "Auto-update trophies and data" || echo "No changes to commit"
          git push
          
